version: '3'
services:
    frontend-nginx:
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
            - ./frontend:/var/www/frontend
        ports:
            - "8080:80"

    api-php-fpm:
        build:
            context: ./api/docker
            dockerfile: php-fpm.docker
        volumes:
            - ./api:/var/www/api
            - ./api/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - api-postgres

    api-php-cli:
        build:
            context: ./api/docker
            dockerfile: php-cli.docker
        volumes:
            - ./api:/var/www/api
            - ./api/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - api-postgres

    api-postgres:
        image: postgres:9.6-alpine
        volumes:
            - ./api/var/docker/postgres:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=api"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=api"
        ports:
            - "54321:5432"

    api-nginx:
        build:
            context: ./api/docker
            dockerfile: nginx.docker
        volumes:
            - ./api:/var/www/api
        ports:
            - "8081:80"
        depends_on:
            -   api-php-fpm

    frontend-nodejs:
        build:
            context: ./frontend/docker
            dockerfile: vue.docker
        volumes:
            - ./frontend:/app
        ports:
            - "8082:8080"
