version: '3'
services:
    frontend-nginx:
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
            - ./frontend:/var/www/frontend
        ports:
            - "8080:80"

    api-php-fpm:
        build:
            context: ./api/docker
            dockerfile: php-fpm.docker
        volumes:
            - ./api:/var/www/api

    api-nginx:
        build:
            context: ./api/docker
            dockerfile: nginx.docker
        volumes:
            - ./api:/var/www/api
        ports:
            - "8081:80"

    frontend-nodejs:
        build:
            context: ./frontend/docker
            dockerfile: vue.docker
        volumes:
            - ./frontend:/app
        ports:
            - "8082:8080"
